### ISSUE TITLE
Functie API_draw_text programmeren

### ISSUE THREAD

**Issue by tijmcraft** [Ragazzoforte/23.24-D-Softwareontwikkeling#17]
DOD:
de functie API_draw_text kan met behulp van de doorgegeven argumenten tekst op het VGA scherm afbeelden en kan een error genereren wanneer alle tekst buiten het tekenveld ligt en een warning wanneer een gedeelte van de tekst buiten het tekenveld ligt.

**Comment by Ragazzoforte** [comment]
De functie werkt nagenoeg. Alleen enkele breede letters waarvan de bitmap breder is dan 8 bits vind hij nog niet leuk. voor de rest werkt hij volgensmij perfect.

**Comment by Ragazzoforte** [comment]
pull request aangemaakt
