### ISSUE TITLE
Functie API_draw_bitmap programmeren

### ISSUE THREAD

**Issue by tijmcraft** [Ragazzoforte/23.24-D-Softwareontwikkeling#20]
DOD:
de functie API_draw_bitmap kan met behulp van de doorgegeven argumenten simpele afbeeldingen (bitmaps) op het VGA scherm afbeelden en kan een error genereren wanneer de origin buiten het tekenveld ligt en een warning wanneer een gedeelte van de afbeelding buiten het tekenveld ligt.

**Comment by Ragazzoforte** [comment]
smiley's en pijlen werken, error tree moet er nog in komen.

usage:
API_draw_bitmap (x, y, bitmap nummer);
#define SMILEY_HAPPY 1
#define SMILEY_SAD 2
#define ARROW_UP 3
#define ARROW_RIGHT 4
#define ARROW_DOWN 5
#define ARROW_LEFT 6
#define MEGAMAN 7

**Comment by Ragazzoforte** [comment]
pull request aangemaakt
