### ISSUE TITLE
Platform.io installeren

### ISSUE THREAD

**Issue by tijmcraft** [Ragazzoforte/23.24-D-Softwareontwikkeling#3]
DOD:
De STM32f407 kan geprogrameerd worden vanuit VScode.

**Comment by TimWannet** [comment]
Werkt niet goed genoeg. 
Fout: 
- Maakt extra gitignore aan wanneer compiled
- Kan geen middleware gebruikt worden vanuit de extentie

Branch aangemaakt om een andere extentie te testen.
