### ISSUE TITLE
Doxygen werkt volledig

### ISSUE THREAD

**Issue by tijmcraft** [Ragazzoforte/23.24-D-Softwareontwikkeling#4]
DOD: Met behulp van Doxygen comments kan er een HTML pagina gemaakt worden. Alle comments kunnen hierin gevisualiseerd worden.

**Comment by Ragazzoforte** [comment]
https://satviksr.medium.com/automatically-publish-documentation-of-your-code-using-github-actions-and-doxygen-e9aaa75f6347

Uitleg hoe we dit mooi werkend kunnen krijgen
